[package]
name = "comm"
version = "0.1.0"
authors = ["Zac Stewart <zgstewart@gmail.com>"]

[dependencies]
mio = "0.5.0"
num = "0.1.31"
protobuf = "1.0.18"
rust-crypto = "0.2.35"
rustc-serialize = "0.3.19"
time = "0.1.35"
